name: note_taking_application
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path: ^1.8.1
  #Database storage
  sqflite: ^2.0.0+3
  # format DateTime
  intl: ^0.17.0
  #Display todos in grid
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  flutter_launcher_icons: "^0.9.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  image_path_android: "./assets/logo.png"
  image_path_ios: "./assets/logo.png" 
  android: true
  ios: true
  


flutter:
  uses-material-design: true

  #
